// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: mcp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MCPTransportType represents the transport mechanism for MCP communication
type MCPTransportType int32

const (
	MCPTransportType_MCP_TRANSPORT_TYPE_UNKNOWN MCPTransportType = 0
	MCPTransportType_MCP_TRANSPORT_TYPE_STDIO   MCPTransportType = 1
	MCPTransportType_MCP_TRANSPORT_TYPE_HTTP    MCPTransportType = 2
	MCPTransportType_MCP_TRANSPORT_TYPE_SSE     MCPTransportType = 3
)

// Enum value maps for MCPTransportType.
var (
	MCPTransportType_name = map[int32]string{
		0: "MCP_TRANSPORT_TYPE_UNKNOWN",
		1: "MCP_TRANSPORT_TYPE_STDIO",
		2: "MCP_TRANSPORT_TYPE_HTTP",
		3: "MCP_TRANSPORT_TYPE_SSE",
	}
	MCPTransportType_value = map[string]int32{
		"MCP_TRANSPORT_TYPE_UNKNOWN": 0,
		"MCP_TRANSPORT_TYPE_STDIO":   1,
		"MCP_TRANSPORT_TYPE_HTTP":    2,
		"MCP_TRANSPORT_TYPE_SSE":     3,
	}
)

func (x MCPTransportType) Enum() *MCPTransportType {
	p := new(MCPTransportType)
	*p = x
	return p
}

func (x MCPTransportType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MCPTransportType) Descriptor() protoreflect.EnumDescriptor {
	return file_mcp_proto_enumTypes[0].Descriptor()
}

func (MCPTransportType) Type() protoreflect.EnumType {
	return &file_mcp_proto_enumTypes[0]
}

func (x MCPTransportType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MCPTransportType.Descriptor instead.
func (MCPTransportType) EnumDescriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{0}
}

// IdentityControlType represents the authentication method used by MCP servers
type IdentityControlType int32

const (
	IdentityControlType_IDENTITY_CONTROL_TYPE_UNKNOWN    IdentityControlType = 0 // Unknown auth method
	IdentityControlType_IDENTITY_CONTROL_TYPE_BASIC_AUTH IdentityControlType = 1 // Username/password
	IdentityControlType_IDENTITY_CONTROL_TYPE_TOKEN      IdentityControlType = 2 // API keys, bearer tokens
	IdentityControlType_IDENTITY_CONTROL_TYPE_OAUTH      IdentityControlType = 3 // OAuth flow
	IdentityControlType_IDENTITY_CONTROL_TYPE_NO_AUTH    IdentityControlType = 4 // No auth
)

// Enum value maps for IdentityControlType.
var (
	IdentityControlType_name = map[int32]string{
		0: "IDENTITY_CONTROL_TYPE_UNKNOWN",
		1: "IDENTITY_CONTROL_TYPE_BASIC_AUTH",
		2: "IDENTITY_CONTROL_TYPE_TOKEN",
		3: "IDENTITY_CONTROL_TYPE_OAUTH",
		4: "IDENTITY_CONTROL_TYPE_NO_AUTH",
	}
	IdentityControlType_value = map[string]int32{
		"IDENTITY_CONTROL_TYPE_UNKNOWN":    0,
		"IDENTITY_CONTROL_TYPE_BASIC_AUTH": 1,
		"IDENTITY_CONTROL_TYPE_TOKEN":      2,
		"IDENTITY_CONTROL_TYPE_OAUTH":      3,
		"IDENTITY_CONTROL_TYPE_NO_AUTH":    4,
	}
)

func (x IdentityControlType) Enum() *IdentityControlType {
	p := new(IdentityControlType)
	*p = x
	return p
}

func (x IdentityControlType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentityControlType) Descriptor() protoreflect.EnumDescriptor {
	return file_mcp_proto_enumTypes[1].Descriptor()
}

func (IdentityControlType) Type() protoreflect.EnumType {
	return &file_mcp_proto_enumTypes[1]
}

func (x IdentityControlType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdentityControlType.Descriptor instead.
func (IdentityControlType) EnumDescriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{1}
}

var File_mcp_proto protoreflect.FileDescriptor

const file_mcp_proto_rawDesc = "" +
	"\n" +
	"\tmcp.proto\x12\x05proto*\x89\x01\n" +
	"\x10MCPTransportType\x12\x1e\n" +
	"\x1aMCP_TRANSPORT_TYPE_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18MCP_TRANSPORT_TYPE_STDIO\x10\x01\x12\x1b\n" +
	"\x17MCP_TRANSPORT_TYPE_HTTP\x10\x02\x12\x1a\n" +
	"\x16MCP_TRANSPORT_TYPE_SSE\x10\x03*\xc3\x01\n" +
	"\x13IdentityControlType\x12!\n" +
	"\x1dIDENTITY_CONTROL_TYPE_UNKNOWN\x10\x00\x12$\n" +
	" IDENTITY_CONTROL_TYPE_BASIC_AUTH\x10\x01\x12\x1f\n" +
	"\x1bIDENTITY_CONTROL_TYPE_TOKEN\x10\x02\x12\x1f\n" +
	"\x1bIDENTITY_CONTROL_TYPE_OAUTH\x10\x03\x12!\n" +
	"\x1dIDENTITY_CONTROL_TYPE_NO_AUTH\x10\x04B\x10Z\x0einternal/protob\x06proto3"

var (
	file_mcp_proto_rawDescOnce sync.Once
	file_mcp_proto_rawDescData []byte
)

func file_mcp_proto_rawDescGZIP() []byte {
	file_mcp_proto_rawDescOnce.Do(func() {
		file_mcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_proto_rawDesc), len(file_mcp_proto_rawDesc)))
	})
	return file_mcp_proto_rawDescData
}

var file_mcp_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_mcp_proto_goTypes = []any{
	(MCPTransportType)(0),    // 0: proto.MCPTransportType
	(IdentityControlType)(0), // 1: proto.IdentityControlType
}
var file_mcp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mcp_proto_init() }
func file_mcp_proto_init() {
	if File_mcp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_proto_rawDesc), len(file_mcp_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcp_proto_goTypes,
		DependencyIndexes: file_mcp_proto_depIdxs,
		EnumInfos:         file_mcp_proto_enumTypes,
	}.Build()
	File_mcp_proto = out.File
	file_mcp_proto_goTypes = nil
	file_mcp_proto_depIdxs = nil
}
