// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: scan.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RiskSeverity represents security risk levels
type RiskSeverity int32

const (
	RiskSeverity_RISK_SEVERITY_UNKNOWN  RiskSeverity = 0
	RiskSeverity_RISK_SEVERITY_LOW      RiskSeverity = 1
	RiskSeverity_RISK_SEVERITY_MEDIUM   RiskSeverity = 2
	RiskSeverity_RISK_SEVERITY_HIGH     RiskSeverity = 3
	RiskSeverity_RISK_SEVERITY_CRITICAL RiskSeverity = 4
)

// Enum value maps for RiskSeverity.
var (
	RiskSeverity_name = map[int32]string{
		0: "RISK_SEVERITY_UNKNOWN",
		1: "RISK_SEVERITY_LOW",
		2: "RISK_SEVERITY_MEDIUM",
		3: "RISK_SEVERITY_HIGH",
		4: "RISK_SEVERITY_CRITICAL",
	}
	RiskSeverity_value = map[string]int32{
		"RISK_SEVERITY_UNKNOWN":  0,
		"RISK_SEVERITY_LOW":      1,
		"RISK_SEVERITY_MEDIUM":   2,
		"RISK_SEVERITY_HIGH":     3,
		"RISK_SEVERITY_CRITICAL": 4,
	}
)

func (x RiskSeverity) Enum() *RiskSeverity {
	p := new(RiskSeverity)
	*p = x
	return p
}

func (x RiskSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_scan_proto_enumTypes[0].Descriptor()
}

func (RiskSeverity) Type() protoreflect.EnumType {
	return &file_scan_proto_enumTypes[0]
}

func (x RiskSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskSeverity.Descriptor instead.
func (RiskSeverity) EnumDescriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{0}
}

// FindingType represents the type of security finding
type FindingType int32

const (
	FindingType_FINDING_TYPE_UNKNOWN FindingType = 0
	FindingType_FINDING_TYPE_SCA     FindingType = 1 // Software Composition Analysis
	FindingType_FINDING_TYPE_SECRETS FindingType = 2 // Secret detection
	FindingType_FINDING_TYPE_SAST    FindingType = 3 // Static Application Security Testing
)

// Enum value maps for FindingType.
var (
	FindingType_name = map[int32]string{
		0: "FINDING_TYPE_UNKNOWN",
		1: "FINDING_TYPE_SCA",
		2: "FINDING_TYPE_SECRETS",
		3: "FINDING_TYPE_SAST",
	}
	FindingType_value = map[string]int32{
		"FINDING_TYPE_UNKNOWN": 0,
		"FINDING_TYPE_SCA":     1,
		"FINDING_TYPE_SECRETS": 2,
		"FINDING_TYPE_SAST":    3,
	}
)

func (x FindingType) Enum() *FindingType {
	p := new(FindingType)
	*p = x
	return p
}

func (x FindingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FindingType) Descriptor() protoreflect.EnumDescriptor {
	return file_scan_proto_enumTypes[1].Descriptor()
}

func (FindingType) Type() protoreflect.EnumType {
	return &file_scan_proto_enumTypes[1]
}

func (x FindingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FindingType.Descriptor instead.
func (FindingType) EnumDescriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{1}
}

// Finding represents a security finding from a scan
type Finding struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Tool     string                 `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`
	Type     FindingType            `protobuf:"varint,2,opt,name=type,proto3,enum=proto.FindingType" json:"type,omitempty"`
	Severity RiskSeverity           `protobuf:"varint,3,opt,name=severity,proto3,enum=proto.RiskSeverity" json:"severity,omitempty"`
	RuleId   string                 `protobuf:"bytes,4,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Title    string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	File     string                 `protobuf:"bytes,6,opt,name=file,proto3" json:"file,omitempty"`       // Optional
	Line     int32                  `protobuf:"varint,7,opt,name=line,proto3" json:"line,omitempty"`      // Optional
	Message  string                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"` // Optional
	// SCA-specific (optional but useful)
	Package       string `protobuf:"bytes,9,opt,name=package,proto3" json:"package,omitempty"`  // Optional
	Version       string `protobuf:"bytes,10,opt,name=version,proto3" json:"version,omitempty"` // Optional
	Fixed         string `protobuf:"bytes,11,opt,name=fixed,proto3" json:"fixed,omitempty"`     // Optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_scan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{0}
}

func (x *Finding) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *Finding) GetType() FindingType {
	if x != nil {
		return x.Type
	}
	return FindingType_FINDING_TYPE_UNKNOWN
}

func (x *Finding) GetSeverity() RiskSeverity {
	if x != nil {
		return x.Severity
	}
	return RiskSeverity_RISK_SEVERITY_UNKNOWN
}

func (x *Finding) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *Finding) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Finding) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Finding) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Finding) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Finding) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *Finding) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Finding) GetFixed() string {
	if x != nil {
		return x.Fixed
	}
	return ""
}

var File_scan_proto protoreflect.FileDescriptor

const file_scan_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"scan.proto\x12\x05proto\"\xb1\x02\n" +
	"\aFinding\x12\x12\n" +
	"\x04tool\x18\x01 \x01(\tR\x04tool\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.proto.FindingTypeR\x04type\x12/\n" +
	"\bseverity\x18\x03 \x01(\x0e2\x13.proto.RiskSeverityR\bseverity\x12\x17\n" +
	"\arule_id\x18\x04 \x01(\tR\x06ruleId\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x12\n" +
	"\x04file\x18\x06 \x01(\tR\x04file\x12\x12\n" +
	"\x04line\x18\a \x01(\x05R\x04line\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\x12\x18\n" +
	"\apackage\x18\t \x01(\tR\apackage\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\tR\aversion\x12\x14\n" +
	"\x05fixed\x18\v \x01(\tR\x05fixed*\x8e\x01\n" +
	"\fRiskSeverity\x12\x19\n" +
	"\x15RISK_SEVERITY_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11RISK_SEVERITY_LOW\x10\x01\x12\x18\n" +
	"\x14RISK_SEVERITY_MEDIUM\x10\x02\x12\x16\n" +
	"\x12RISK_SEVERITY_HIGH\x10\x03\x12\x1a\n" +
	"\x16RISK_SEVERITY_CRITICAL\x10\x04*n\n" +
	"\vFindingType\x12\x18\n" +
	"\x14FINDING_TYPE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10FINDING_TYPE_SCA\x10\x01\x12\x18\n" +
	"\x14FINDING_TYPE_SECRETS\x10\x02\x12\x15\n" +
	"\x11FINDING_TYPE_SAST\x10\x03B\x10Z\x0einternal/protob\x06proto3"

var (
	file_scan_proto_rawDescOnce sync.Once
	file_scan_proto_rawDescData []byte
)

func file_scan_proto_rawDescGZIP() []byte {
	file_scan_proto_rawDescOnce.Do(func() {
		file_scan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scan_proto_rawDesc), len(file_scan_proto_rawDesc)))
	})
	return file_scan_proto_rawDescData
}

var file_scan_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_scan_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_scan_proto_goTypes = []any{
	(RiskSeverity)(0), // 0: proto.RiskSeverity
	(FindingType)(0),  // 1: proto.FindingType
	(*Finding)(nil),   // 2: proto.Finding
}
var file_scan_proto_depIdxs = []int32{
	1, // 0: proto.Finding.type:type_name -> proto.FindingType
	0, // 1: proto.Finding.severity:type_name -> proto.RiskSeverity
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_scan_proto_init() }
func file_scan_proto_init() {
	if File_scan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scan_proto_rawDesc), len(file_scan_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scan_proto_goTypes,
		DependencyIndexes: file_scan_proto_depIdxs,
		EnumInfos:         file_scan_proto_enumTypes,
		MessageInfos:      file_scan_proto_msgTypes,
	}.Build()
	File_scan_proto = out.File
	file_scan_proto_goTypes = nil
	file_scan_proto_depIdxs = nil
}
