package main

import (
	"os"
	"path/filepath"
	"testing"
)

func mustWriteTempFile(t *testing.T, dir, name string) string {
	t.Helper()
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, []byte("x"), 0644); err != nil {
		t.Fatalf("failed to create temp file %s: %v", path, err)
	}
	return path
}

// TestCleanupGeneratedFiles_EmptyOutputPath guards the config-scan/pentest
// "-o was user-specified" case: the caller intentionally leaves outputPath
// empty so a user-chosen output file is never auto-deleted. cleanupGeneratedFiles
// must treat that as "nothing to remove here", not as an error.
func TestCleanupGeneratedFiles_EmptyOutputPath(t *testing.T) {
	dir := t.TempDir()
	toolsFile := mustWriteTempFile(t, dir, "tools.json")
	testFile := mustWriteTempFile(t, dir, "test.yaml")

	err := cleanupGeneratedFiles("", toolsFile, testFile, "")
	if err != nil {
		t.Fatalf("cleanupGeneratedFiles with empty outputPath returned error: %v", err)
	}

	if _, statErr := os.Stat(toolsFile); !os.IsNotExist(statErr) {
		t.Errorf("expected toolsFile %s to be removed", toolsFile)
	}
	if _, statErr := os.Stat(testFile); !os.IsNotExist(statErr) {
		t.Errorf("expected testFile %s to be removed", testFile)
	}
}

// TestCleanupGeneratedFiles_AllEmpty is a pure no-op: every path is "",
// nothing was auto-generated, nothing should be touched, no error.
func TestCleanupGeneratedFiles_AllEmpty(t *testing.T) {
	if err := cleanupGeneratedFiles("", "", "", ""); err != nil {
		t.Fatalf("cleanupGeneratedFiles with all-empty paths returned error: %v", err)
	}
}

// TestCleanupGeneratedFiles_NonExistentPathsAreTolerated extends the
// tolerance the other three arguments already had (os.IsNotExist is ignored)
// to outputPath, which previously lacked both the empty-string guard and the
// IsNotExist tolerance.
func TestCleanupGeneratedFiles_NonExistentPathsAreTolerated(t *testing.T) {
	dir := t.TempDir()
	missing := filepath.Join(dir, "does-not-exist.sarif.json")

	if err := cleanupGeneratedFiles(missing, "", "", ""); err != nil {
		t.Fatalf("cleanupGeneratedFiles with a non-existent outputPath returned error: %v", err)
	}
}

// TestCleanupGeneratedFiles_RemovesEverythingWhenAutoGenerated covers the
// normal auto-generated-files case: all four paths present and real.
func TestCleanupGeneratedFiles_RemovesEverythingWhenAutoGenerated(t *testing.T) {
	dir := t.TempDir()
	outputFile := mustWriteTempFile(t, dir, "findings.sarif.json")
	toolsFile := mustWriteTempFile(t, dir, "tools.json")
	testFile := mustWriteTempFile(t, dir, "test.yaml")
	testPlanDir := filepath.Join(dir, "pentest_plans")
	if err := os.Mkdir(testPlanDir, 0755); err != nil {
		t.Fatalf("failed to create test plan dir: %v", err)
	}

	if err := cleanupGeneratedFiles(outputFile, toolsFile, testFile, testPlanDir); err != nil {
		t.Fatalf("cleanupGeneratedFiles returned error: %v", err)
	}

	for _, p := range []string{outputFile, toolsFile, testFile, testPlanDir} {
		if _, statErr := os.Stat(p); !os.IsNotExist(statErr) {
			t.Errorf("expected %s to be removed", p)
		}
	}
}

func TestExecutionScannerMatches(t *testing.T) {
	cases := []struct {
		exec, tool string
		want       bool
	}{
		{"osv", "osv", true},
		{"osv", "osv-scanner", true},
		{"osv", "sca", true},
		{"gitleaks", "gitleaks", true},
		{"gitleaks", "secrets", true},
		{"sast", "sast", true},
		{"sast", "semgrep", true},
		{"osv", "gitleaks", false},
		{"gitleaks", "sast", false},
		{"sast", "osv", false},
		{"OSV", "osv", true},
		{"SAST", "SAST", true},
	}
	for _, tc := range cases {
		got := executionScannerMatches(tc.exec, tc.tool)
		if got != tc.want {
			t.Errorf("executionScannerMatches(%q, %q) = %v, want %v", tc.exec, tc.tool, got, tc.want)
		}
	}
}

func TestRepoRelativeSlash(t *testing.T) {
	cases := []struct {
		root, abs string
		want      string
	}{
		{"/repo", "/repo/src/main.go", "src/main.go"},
		{"/repo", "", ""},
		{"/repo", "/repo", "."},
	}
	for _, tc := range cases {
		got := repoRelativeSlash(tc.root, tc.abs)
		if got != tc.want {
			t.Errorf("repoRelativeSlash(%q, %q) = %q, want %q", tc.root, tc.abs, got, tc.want)
		}
	}
}
