package main

import (
	"os"
	"path/filepath"
	"testing"

	"mcpxray/internal/targetresolve"
	"mcpxray/proto"
)

func mustWriteTempFile(t *testing.T, dir, name string) string {
	t.Helper()
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, []byte("x"), 0644); err != nil {
		t.Fatalf("failed to create temp file %s: %v", path, err)
	}
	return path
}

// TestCleanupGeneratedFiles_EmptyOutputPath guards the config-scan/pentest
// "-o was user-specified" case: the caller intentionally leaves outputPath
// empty so a user-chosen output file is never auto-deleted. cleanupGeneratedFiles
// must treat that as "nothing to remove here", not as an error.
func TestCleanupGeneratedFiles_EmptyOutputPath(t *testing.T) {
	dir := t.TempDir()
	toolsFile := mustWriteTempFile(t, dir, "tools.json")
	testFile := mustWriteTempFile(t, dir, "test.yaml")

	err := cleanupGeneratedFiles("", toolsFile, testFile, "")
	if err != nil {
		t.Fatalf("cleanupGeneratedFiles with empty outputPath returned error: %v", err)
	}

	if _, statErr := os.Stat(toolsFile); !os.IsNotExist(statErr) {
		t.Errorf("expected toolsFile %s to be removed", toolsFile)
	}
	if _, statErr := os.Stat(testFile); !os.IsNotExist(statErr) {
		t.Errorf("expected testFile %s to be removed", testFile)
	}
}

// TestCleanupGeneratedFiles_AllEmpty is a pure no-op: every path is "",
// nothing was auto-generated, nothing should be touched, no error.
func TestCleanupGeneratedFiles_AllEmpty(t *testing.T) {
	if err := cleanupGeneratedFiles("", "", "", ""); err != nil {
		t.Fatalf("cleanupGeneratedFiles with all-empty paths returned error: %v", err)
	}
}

// TestCleanupGeneratedFiles_NonExistentPathsAreTolerated extends the
// tolerance the other three arguments already had (os.IsNotExist is ignored)
// to outputPath, which previously lacked both the empty-string guard and the
// IsNotExist tolerance.
func TestCleanupGeneratedFiles_NonExistentPathsAreTolerated(t *testing.T) {
	dir := t.TempDir()
	missing := filepath.Join(dir, "does-not-exist.sarif.json")

	if err := cleanupGeneratedFiles(missing, "", "", ""); err != nil {
		t.Fatalf("cleanupGeneratedFiles with a non-existent outputPath returned error: %v", err)
	}
}

// TestCleanupGeneratedFiles_RemovesEverythingWhenAutoGenerated covers the
// normal auto-generated-files case: all four paths present and real.
func TestCleanupGeneratedFiles_RemovesEverythingWhenAutoGenerated(t *testing.T) {
	dir := t.TempDir()
	outputFile := mustWriteTempFile(t, dir, "findings.sarif.json")
	toolsFile := mustWriteTempFile(t, dir, "tools.json")
	testFile := mustWriteTempFile(t, dir, "test.yaml")
	testPlanDir := filepath.Join(dir, "pentest_plans")
	if err := os.Mkdir(testPlanDir, 0755); err != nil {
		t.Fatalf("failed to create test plan dir: %v", err)
	}

	if err := cleanupGeneratedFiles(outputFile, toolsFile, testFile, testPlanDir); err != nil {
		t.Fatalf("cleanupGeneratedFiles returned error: %v", err)
	}

	for _, p := range []string{outputFile, toolsFile, testFile, testPlanDir} {
		if _, statErr := os.Stat(p); !os.IsNotExist(statErr) {
			t.Errorf("expected %s to be removed", p)
		}
	}
}

func TestExecutionScannerMatches(t *testing.T) {
	cases := []struct {
		exec, tool string
		want       bool
	}{
		{"osv", "osv", true},
		{"osv", "osv-scanner", true},
		{"osv", "sca", true},
		{"gitleaks", "gitleaks", true},
		{"gitleaks", "secrets", true},
		{"sast", "sast", true},
		{"sast", "semgrep", true},
		{"osv", "gitleaks", false},
		{"gitleaks", "sast", false},
		{"sast", "osv", false},
		{"OSV", "osv", true},
		{"SAST", "SAST", true},
	}
	for _, tc := range cases {
		got := executionScannerMatches(tc.exec, tc.tool)
		if got != tc.want {
			t.Errorf("executionScannerMatches(%q, %q) = %v, want %v", tc.exec, tc.tool, got, tc.want)
		}
	}
}

func TestExplicitTargetRequested(t *testing.T) {
	cases := []struct {
		name       string
		targetFlag string
		targetIDs  []string
		allTargets bool
		want       bool
	}{
		{"nothing requested", "", nil, false, false},
		{"target name requested", "my-server", nil, false, true},
		{"target id requested", "", []string{"t-1"}, false, true},
		{"all targets requested", "", nil, true, true},
		{"empty target-id slice is not a request", "", []string{}, false, false},
	}
	for _, tc := range cases {
		got := explicitTargetRequested(tc.targetFlag, tc.targetIDs, tc.allTargets)
		if got != tc.want {
			t.Errorf("%s: explicitTargetRequested(%q, %v, %v) = %v, want %v", tc.name, tc.targetFlag, tc.targetIDs, tc.allTargets, got, tc.want)
		}
	}
}

// TestAttributeWorkspaceRootFallback proves two things at once: a finding
// from a registered workspace-root fallback path is correctly credited to
// every target plan.FileOwnership says relies on it, and a finding whose
// path was NOT registered (shouldn't happen in practice -- ScanRootOwnFiles
// only ever scans the repo root's own direct files -- but must never
// silently join the report as an unowned repo-global finding) is skipped.
func TestAttributeWorkspaceRootFallback(t *testing.T) {
	repoRoot := t.TempDir()
	plan := &targetresolve.ScanPlan{
		FileOwnership: map[string]*targetresolve.FileOwnership{
			"package-lock.json": {
				TargetIDs:    []string{"t-a", "t-b"},
				ComponentIDs: []string{"c-a", "c-b"},
				Relation:     targetresolve.RelationWorkspaceRoot,
				Context:      "production",
			},
		},
	}
	owned := &proto.Finding{Tool: "osv", RuleId: "CVE-1", File: filepath.Join(repoRoot, "package-lock.json"), Package: "lodash", Version: "4.17.15"}
	unowned := &proto.Finding{Tool: "osv", RuleId: "CVE-2", File: filepath.Join(repoRoot, "unrelated-file.json"), Package: "foo", Version: "1.0.0"}

	got := attributeWorkspaceRootFallback([]*proto.Finding{owned, unowned}, repoRoot, plan)

	if len(got) != 1 {
		t.Fatalf("attributed = %d findings, want 1 (the unregistered path must be skipped)", len(got))
	}
	af := got[0]
	if af.Finding != owned {
		t.Errorf("expected the attributed finding to be the registered one")
	}
	if af.Relation != targetresolve.RelationWorkspaceRoot {
		t.Errorf("Relation = %q, want %q", af.Relation, targetresolve.RelationWorkspaceRoot)
	}
	if len(af.TargetIDs) != 2 || af.TargetIDs[0] != "t-a" || af.TargetIDs[1] != "t-b" {
		t.Errorf("TargetIDs = %v, want both t-a and t-b", af.TargetIDs)
	}
	if af.ScanUnitID != "workspace-root-fallback" {
		t.Errorf("ScanUnitID = %q, want %q", af.ScanUnitID, "workspace-root-fallback")
	}
}

func TestRepoRelativeSlash(t *testing.T) {
	cases := []struct {
		root, abs string
		want      string
	}{
		{"/repo", "/repo/src/main.go", "src/main.go"},
		{"/repo", "", ""},
		{"/repo", "/repo", "."},
	}
	for _, tc := range cases {
		got := repoRelativeSlash(tc.root, tc.abs)
		if got != tc.want {
			t.Errorf("repoRelativeSlash(%q, %q) = %q, want %q", tc.root, tc.abs, got, tc.want)
		}
	}
}
